# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CatsTower' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CatsTower
  pod 'Alamofire'
  pod 'RealmSwift', '~> 10'

  target 'CatsTowerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CatsTowerUITests' do
    # Pods for testing
  end

end
